
FROM php:8.0.10-fpm-buster

RUN apt-get -y update \
    && apt-get install -y libicu-dev autoconf automake \ 
    && docker-php-ext-configure intl \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
    && docker-php-ext-install intl pdo pdo_mysql

WORKDIR /app