-- MySQL Script generated by MySQL Workbench
-- Sat Dec 23 09:49:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `loteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria` (
  `id` BINARY(16) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `slug` VARCHAR(120) NOT NULL,
  `dezena` JSON NOT NULL,
  `premiar` JSON NOT NULL,
  `marcar` JSON NOT NULL,
  `logo` VARCHAR(255) NOT NULL DEFAULT 'logo-default-600x200.png',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `api` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concurso` (
  `id` BINARY(16) NOT NULL,
  `loteria_id` BINARY(16) NOT NULL,
  `numero` INT UNSIGNED NULL,
  `apuracao_data` DATETIME NULL,
  `rateio_premio` JSON NULL,
  `local` VARCHAR(60) NULL,
  `municipio` VARCHAR(60) NULL,
  `uf` VARCHAR(2) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `dezena` JSON NULL,
  PRIMARY KEY (`id`, `loteria_id`),
  INDEX `fk_concurso_loteria_idx` (`loteria_id` ASC),
  CONSTRAINT `fk_concurso_loteria`
    FOREIGN KEY (`loteria_id`)
    REFERENCES `loteria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` BINARY(16) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `password` VARCHAR(255) NOT NULL,
  `roles` JSON NOT NULL,
  `celular` VARCHAR(20) NULL,
  `is_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `last_login_at` DATETIME NULL,
  `last_login_ip` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolao` (
  `id` BINARY(16) NOT NULL,
  `nome` VARCHAR(120) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `comprovante_aposta` VARCHAR(255) NULL,
  `usuario_id` BINARY(16) NOT NULL,
  `concurso_id` BINARY(16) NOT NULL,
  `valor_cota` DECIMAL(7,2) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_bolao_usuario_idx` (`usuario_id` ASC),
  INDEX `fk_bolao_concurso_idx` (`concurso_id` ASC),
  CONSTRAINT `fk_bolao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bolao_concurso1`
    FOREIGN KEY (`concurso_id`)
    REFERENCES `concurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aposta` (
  `id` BINARY(16) NOT NULL,
  `concurso_id` BINARY(16) NOT NULL,
  `usuario_id` BINARY(16) NOT NULL,
  `dezena` JSON NOT NULL,
  `bolao_id` BINARY(16) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `is_conferido` TINYINT(1) NOT NULL DEFAULT 0,
  `acerto` INT NULL,
  `is_premiado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_aposta_usuario_idx` (`usuario_id` ASC),
  INDEX `fk_aposta_bolao_idx` (`bolao_id` ASC),
  INDEX `fk_aposta_concurso_idx` (`concurso_id` ASC),
  CONSTRAINT `fk_aposta_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aposta_bolao`
    FOREIGN KEY (`bolao_id`)
    REFERENCES `bolao` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aposta_concurso`
    FOREIGN KEY (`concurso_id`)
    REFERENCES `concurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apostador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apostador` (
  `id` BINARY(16) NOT NULL,
  `bolao_id` BINARY(16) NOT NULL,
  `usuario_id` BINARY(16) NULL,
  `is_pago` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `comprovante` VARCHAR(255) NULL COMMENT 'Nome do arquivo com o comprovante de pagamento da cota do bolão.',
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(180) NULL,
  `celular` VARCHAR(20) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `quantidade_cota` INT UNSIGNED ZEROFILL NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_apostador_bolao_idx` (`bolao_id` ASC),
  INDEX `fk_apostador_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_apostador_bolao`
    FOREIGN KEY (`bolao_id`)
    REFERENCES `bolao` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apostador_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messenger_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messenger_messages` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `body` LONGTEXT NOT NULL,
  `headers` LONGTEXT NOT NULL,
  `queue_name` VARCHAR(190) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `available_at` DATETIME NOT NULL,
  `delivered_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `queue_name_INDEX` (`queue_name` ASC),
  INDEX `available_at_INDEX` (`available_at` ASC),
  INDEX `delivered_at_INDEX` (`delivered_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rememberme_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rememberme_token` (
  `series` VARCHAR(88) NOT NULL,
  `value` VARCHAR(88) NOT NULL,
  `lastUsed` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `class` VARCHAR(100) NOT NULL,
  `username` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`series`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reset_password_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reset_password_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `selector` VARCHAR(20) NOT NULL,
  `hashed_token` VARCHAR(100) NOT NULL,
  `requested_at` DATETIME NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `usuario_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reset_password_request_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_reset_password_request_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
